### ISSUE TITLE
视频合成时clone is not a function

### ISSUE THREAD

**Issue by gubeils** [hughfenghen/WebAV#100]
![image](https://github.com/hughfenghen/WebAV/assets/102788024/f8f6b15e-fd21-49bd-901f-ae0c1cae23f8)

设置了main: true ，显示一直克隆
![c976de0ad8ac90adda4d5c5e08ff594](https://github.com/hughfenghen/WebAV/assets/102788024/f7d2f79b-5781-48a6-84db-4e888eedc629)

源代码在这
![7a74b8626b19de477490ad60d0f3d9b](https://github.com/hughfenghen/WebAV/assets/102788024/bef744f3-fcff-4614-ad82-44b08768f217)

**Comment by hughfenghen** [comment]
新版本 需要自定义 clip 实现 clone 方法

**Comment by hughfenghen** [comment]
`IClip.clone` 可能是一个错误的设计，后续考虑将 Clip 设计成不可变对象，变更操作返回新对象，原对象不变
以消除 clone，简化使用。

**Comment by hughfenghen** [comment]
经过思考，`IClip.clone` 无法消除，必须保留。
IClip 是素材（视频、音频、图片等）抽象， 素材必须实现 `clone`。

为了让同一个素材在用户编辑预览的同时，后台进行视频合成导出，而不会不相互干扰，素材必须允许 clone。

所以，碰到改错误，请给自定义素材实现 `IClip.clone` 方法，可以参考项目中 `MP4Clip、AudioClip` 的代码
