### ISSUE TITLE
fetch 在微前端的应用里被重复调用，会导致body的ReadableStream locked:true,MP4Clip拿不到audio

### ISSUE THREAD

**Issue by teyra** [hughfenghen/WebAV#101]
控制台打印错误：`Cannot read properties of undefind (reading 'audio')`

<img width="952" alt="image" src="https://github.com/hughfenghen/WebAV/assets/3307051/9d35161a-c42c-460a-bf78-3aada85174c7">

**Comment by hughfenghen** [comment]
无法读取的流  SDK 会抛出错误，方便分析原因，具体问题（无法读取的原因）需要你解决

**Comment by hughfenghen** [comment]
被 `locked` 的流当前是有明确的错误信息的。
并不会如你截图所示，打印不明确的错误。
@teyra 请确认下

![image](https://github.com/hughfenghen/WebAV/assets/3307051/d819e34a-dffb-41d3-95cf-c4319182d115)
