### ISSUE TITLE
关于AV-Canvas为什么采用一直在计数的workerTimer?

### ISSUE THREAD

**Issue by chenzhutian** [hughfenghen/WebAV#118]
你好! 
我最近在阅读代码的时候, 发现AV-Canvas的play / pause 机制跟一般的视频引擎不太一样.
一般的视频引擎, 比如 [react-timeline-editor](https://github.com/xzdarcy/react-timeline-editor/blob/master/src/engine/engine.ts#L159), 是在用户调用`play()`函数之后再设置一个set Interval或者调用requestAnimationFrame, 然后当用户调用`pause()`后再停掉.

而在AV-Canvas中, 是采用了一个一直在运行的workerTimer, 然后通过设置`playState`的step来控制播放和暂停的.
想问一下作者这样设计的考虑是什么呢? 会不会导致额外的运行开销呢? (因为有一个timer一直在跑)
谢谢!

**Comment by hughfenghen** [comment]
请参考作者的文章[JS 定时器时长控制细节](https://hughfenghen.github.io/posts/2023/06/15/timer-delay/#后台页面-最小延迟-1000ms)

> 为了优化后台 tab 的加载损耗（以及降低耗电量），在未被激活的 tab 中定时器的最小延时限制为 1000ms。
这经常导致一些看似正常工作的程序，后台运行一段时间后就出现 bug 了。
甚至导致需要常驻后台的主要功能无法正常工作。
解决方法：使用 WebWorker 中的 setInterval 向主线程发送消息（postmessage），主线程会立即执行。
理解浏览器限制的原因，如非必要不要随意使用该方法

Web 页面长时间置于后台，定时器将被降低频率。

---

实际上 AVCanvas （剪辑 UI）可用普通的 setInterval 来实现刷新，因为：
1. 用户交互，刷新画面，页面肯定是处于前台的
2. 预览播放一般持续时间也不会太长

而 Combinator （合成视频）则必须由 workerTimer 来驱动，因为合成视频耗时较长，且常常处于后台。

因为我现实现的 Combinator  并且已经封装好了 workerTimer 函数，用起来也简单，所以此处直接用了。

**Comment by chenzhutian** [comment]
明白了, 感谢!
