### ISSUE TITLE
Using the av-canvas module in electron to report an error

### ISSUE THREAD

**Issue by Dragon-S** [hughfenghen/WebAV#13]
I use av-recorder and av-canvas modules in electron, av-recorder works fine, but av-canvas reports an error.
(1) The error is as follows
<img width="688" alt="截屏2023-06-30 17 05 14" src="https://github.com/hughfenghen/WebAV/assets/36149358/c2257ed5-214d-4c40-b80e-d2587f04e165">

(2) The relevant codes are as follows
[index.js.zip](https://github.com/hughfenghen/WebAV/files/11914842/index.js.zip)

**Comment by hughfenghen** [comment]
Wait a minute, I will add the main field to the package.json

**Comment by hughfenghen** [comment]
@Dragon-S  fixed by 0.1.26
