### ISSUE TITLE
Recorded MP4 file lacks duration information

### ISSUE THREAD

**Issue by Dragon-S** [hughfenghen/WebAV#15]
Hi, @hughfenghen 

I used your latest demo to record an mp4, but the recorded mp4 file lacks duration information, which makes it impossible to seek in some players.
I couldn't find any information in your code or in the mp4box.js API on how to write duration information. I'm new to audio and video and would appreciate your guidance. Thank you!

Here is the recorded mp4: 

https://github.com/hughfenghen/WebAV/assets/36149358/ae54b4a7-b563-4309-ada9-9bafe808b5d1

<img width="1213" alt="屏幕截图 2023-07-12 103104" src="https://github.com/hughfenghen/WebAV/assets/36149358/c2990766-56f5-4768-b5e8-e493d924e1a8">

**Comment by hughfenghen** [comment]
@Dragon-S 
Because the output is a Fragment mp4 (fMP4), the video duration is the cumulative value of all fragment durations. 
<img width="638" alt="image" src="https://github.com/hughfenghen/WebAV/assets/3307051/015035d3-8e66-4c83-bf4b-873652f23836">

> which makes it impossible to seek in some players.
Most players should support fMP4, can you provide player info？

**Comment by Dragon-S** [comment]
@hughfenghen 
I am using Windows media player, here are the details
<img width="646" alt="屏幕截图 2023-07-12 123104" src="https://github.com/hughfenghen/WebAV/assets/36149358/a07fd520-1e0c-43b9-b3c9-5fd5fd5644b4">

**Comment by Dragon-S** [comment]
@hughfenghen 
These players that come with widows have the same problem
<img width="902" alt="屏幕截图 2023-07-12 123843" src="https://github.com/hughfenghen/WebAV/assets/36149358/1f696c46-089b-4e41-945c-072893ef2c77">
<img width="1281" alt="屏幕截图 2023-07-12 123923" src="https://github.com/hughfenghen/WebAV/assets/36149358/9033a7aa-d10b-479d-a04a-053f0e67589e">

**Comment by hughfenghen** [comment]
The duration is stored in the moov box, the program cannot determine the duration when it starts recording.
Currently using streaming file writing, so there is no way to fix this.

You may be able to choose an fMP4 compatible player such as a browser, or use ffmpeg to add duration.
`ffmpeg -i WebAv-export-1689131950320.mp4 -vcodec copy -acodec copy video_1_fixed.mp4`

**Comment by hughfenghen** [comment]
@Dragon-S Hi, welcome join to discord ：） https://discord.gg/ZD9KF6TV

**Comment by Dragon-S** [comment]
> @Dragon-S Hi, welcome to join discord ：） https://discord.gg/ZD9KF6TV

Already joined, thank you！
