### ISSUE TITLE
There is a memory leak issue in the recording function.

### ISSUE THREAD

**Issue by Dragon-S** [hughfenghen/WebAV#16]
This issue can be reproduced using the demo at https://hughfenghen.github.io/WebAV/demo/record-usermedia.html

During the recording process, the memory usage keeps increasing. Although the browser's garbage collector runs, it is not able to completely free up the memory.

By debugging the code and temporarily disabling certain lines, the memory leak issue is mostly resolved. The problematic code seems to be related to the following line:
```
mp4File.addSample(trackId, s.data, s) 
``` 

The specific code location is as follows:
<img width="647" alt="屏幕截图 2023-07-18 183324" src="https://github.com/hughfenghen/WebAV/assets/36149358/f1020171-4057-44f3-aa01-971c139943b6">
<img width="575" alt="屏幕截图 2023-07-18 183409" src="https://github.com/hughfenghen/WebAV/assets/36149358/d1cad238-9629-49fb-9ee6-6e4cea388e90">

**Comment by hughfenghen** [comment]
@Dragon-S It should be fixed, please confirm.
