### ISSUE TITLE
请问下现在有办法在浏览器中处理 MKV 文件吗？

### ISSUE THREAD

**Issue by tron-billy** [hughfenghen/WebAV#18]
难道只能用 ffmpeg 了吗？😭

**Comment by hughfenghen** [comment]
@tron-billy 
目前有两个办法：
1. 将 mkv 先转成 mp4 （服务器上 ffmpeg 转封装很快的）再下发到浏览器，使用 WebAV 处理
2. 找一个 mkv 的 demuxer，解封装后使用 WebCodecs 解码

WebAV 未来也许会考虑支持其它常见视频协议，但靠谱的demux sdk 太少了，所以近期不会支持

**Comment by tron-billy** [comment]
> @tron-billy 目前有两个办法：
> 
> 1. 将 mkv 先转成 mp4 （服务器上 ffmpeg 转封装很快的）再下发到浏览器，使用 WebAV 处理
> 2. 找一个 mkv 的 demuxer，解封装后使用 WebCodecs 解码
> 
> WebAV 未来也许会考虑支持其它常见视频格式，但靠谱的 demux sdk 太少了，所以近期不会支持

感谢，我再去调研下
