### ISSUE TITLE
在 WebWorker 环境下 await clip.ready 一直报错

### ISSUE THREAD

**Issue by ctcx** [hughfenghen/WebAV#19]
在worker 环境下使用，这一行代码会报错：
await clip.ready;
`
645 av-utils.ts:11 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'length')
    at av-utils.ts:11:25
    at Array.map (<anonymous>)
    at xt (av-utils.ts:11:10)
    at mp4-clip.ts:104:26
    at u (mp4-clip.ts:255:5)
    at h (mp4-clip.ts:249:12)
    at mp4-clip.ts:267:21
`

**Comment by hughfenghen** [comment]
@ctcx  能提供 测试文件么？

**Comment by ctcx** [comment]
`/* eslint-disable no-restricted-globals */

import { MP4Clip } from "@webav/av-cliper";

async function playVideo(cvs: HTMLCanvasElement, file: any) {
    if (!cvs) {
        return;
    }
    const ctx = cvs.getContext("2d");
    if (!ctx) {
        return;
    }

    const clip =
        typeof file == 'string'
            ? new MP4Clip((await fetch(file)).body!)
            : new MP4Clip(file.stream());

    const { width, height } = await clip.ready;

    // 设置画布尺寸
    cvs.width = width;
    cvs.height = height;

    let time = 0;
    var fps = 30;
    var fpsInterval = 1000 / fps;
    var last = new Date().getTime(); //上次执行的时刻
    let frameCount = 0;

    requestAnimationFrame(async function renderVideo() {
        // 执行时的时间
        var now = new Date().getTime();
        var elapsed = now - last;
        // 经过了足够的时间
        if (elapsed <= fpsInterval) {
            requestAnimationFrame(renderVideo);
            return;
        }
        last = now - (elapsed % fpsInterval); //校正当前时间
        const { state, video: videoFrame } = await clip.tick(time);
        if (state === "done") {
            clip.destroy();
            return;
        }
        frameCount++;

        if (videoFrame != null && state === "success") {
            ctx.clearRect(0, 0, cvs.width, cvs.height);
            // 绘制到 Canvas
            ctx.drawImage(
                videoFrame,
                0,
                0,
                videoFrame.codedWidth,
                videoFrame.codedHeight
            );
            // 注意，用完立即 close
            videoFrame.close();
        }
        // 时间单位是 微秒，所以差不多每秒取 30 帧，丢掉多余的帧
        //   time += 33000;
        time += 33000;
        requestAnimationFrame(renderVideo);
    });
}
self.onmessage = (e: MessageEvent<any>) => {
    playVideo(e.data.canvas, e.data.videoFile)
};

export { };`

**Comment by ctcx** [comment]
如果是以new Worker 的方式使用上面的代码就会报错；如果是普通引入则正常。

**Comment by hughfenghen** [comment]
@ctcx 
很遗憾，在 WebWorker 中无法使用 OfflineAudioContext 重采样音频；
现阶段，如果解码带音频的 mp4 只能在 主线程使用 MP4Clip，这个过程不怎么消耗 CPU

我优化了错误日志输出（version：0.1.50），打印了更准确的日志

如果无需使用音频，可以在 MP4Clip 中移除音频，不会报错
https://github.com/hughfenghen/WebAV/blob/main/packages/av-cliper/demo/decode-video-worker.ts#L4

**Comment by ctcx** [comment]
明白了，感谢你的回复，这是一个非常有用的项目，你的工作非常有价值。

**Comment by hughfenghen** [comment]
@ctcx  也许可以使用js或wasm 替代 OfflineAudioContext 来实现重采样，但不知性能怎么样
总之值得一试

这个 issue 先挂在着里，等验证完了来同步结果

**Comment by hughfenghen** [comment]
@ctcx 
在 WebWorker 中使用这个库进行重采样 https://github.com/rochars/wave-resampler，简单验证 MP4Clip 正常运行
你试试没问题就关掉这个 issue 吧

Tips：AudioClip 还不能在 WebWorker 中运行，有需要的话再考虑
