### ISSUE TITLE
生成的视频没有duration，在播放器中不会显示总时长

### ISSUE THREAD

**Issue by qcjiamin** [hughfenghen/WebAV#20]

**Comment by hughfenghen** [comment]
或者在结束的时候，给 moov box 添加 duration 写入文件结尾，需要试试是否可行。

**Comment by hughfenghen** [comment]
> 或者在结束的时候，给 moov box 添加 duration 写入文件结尾，需要试试是否可行。

试过了，将 moov box 移动到 fMP4 文件的末尾处，文件将无法播放。

按这个规范文件描述，moov 应该在 ftyp box 之后，文件的开头处。
https://www.w3.org/2013/12/byte-stream-format-registry/isobmff-byte-stream-format.html

**Comment by hughfenghen** [comment]
很遗憾，目前只能通过ffmpeg 添加 duration：`ffmpeg -i WebAv-export-1689131950320.mp4 -vcodec copy -acodec copy video_1_fixed.mp4`

或者牺牲流式导出文件的能力，在流结束的时候去更新 duration，但我目前认为还不值得。

**Comment by hughfenghen** [comment]
`v0.2.17` 新增一个 API `mp4StreamToOPFSFile` 将 mp4 流保存到临时文件，在流结束时修正 duration 字段

查看完整示例 [修复输出文件不显示时长](https://hughfenghen.github.io/WebAV/demo/4_1-recorder-usermedia#%E4%BF%AE%E5%A4%8D%E8%BE%93%E5%87%BA%E6%96%87%E4%BB%B6%E4%B8%8D%E6%98%BE%E7%A4%BA%E6%97%B6%E9%95%BF)

**Comment by DeanDai** [comment]
> `v0.2.17` 新增一个 API `mp4StreamToOPFSFile` 将 mp4 流保存到临时文件，在流结束时修正 duration 字段 解决 windows Media Player 播放输出文件不显示时长
> 
> 查看完整示例 [修复输出文件不显示时长](https://hughfenghen.github.io/WebAV/demo/4_1-recorder-usermedia#%E4%BF%AE%E5%A4%8D%E8%BE%93%E5%87%BA%E6%96%87%E4%BB%B6%E4%B8%8D%E6%98%BE%E7%A4%BA%E6%97%B6%E9%95%BF)

Hi, seems like the demo is unavailable, may I know how to solve the issue? Thanks

**Comment by hughfenghen** [comment]
@DeanDai 

If you use the `@webav/av-cliper` Combinator to generate videos, this issue has been resolved in the latest version
[commit](https://github.com/bilibili/WebAV/commit/94da2c71cad3b2b1e4d88aa6a7312c6b630becc2#), [DEMO](https://bilibili.github.io/WebAV/demo/2_1-concat-video)

If you use `@webav/av-recorder` to record videos, please refer to this [DEMO](https://bilibili.github.io/WebAV/demo/4_1-recorder-usermedia#%E4%BF%AE%E5%A4%8D%E8%BE%93%E5%87%BA%E6%96%87%E4%BB%B6%E4%B8%8D%E6%98%BE%E7%A4%BA%E6%97%B6%E9%95%BF)

_This project has changed organizations, so the domain name has changed._

**Comment by DeanDai** [comment]
> @DeanDai
> 
> If you use the `@webav/av-cliper` Combinator to generate videos, this issue has been resolved in the latest version [commit](https://github.com/bilibili/WebAV/commit/94da2c71cad3b2b1e4d88aa6a7312c6b630becc2#), [DEMO](https://bilibili.github.io/WebAV/demo/2_1-concat-video)
> 
> If you use `@webav/av-recorder` to record videos, please refer to this [DEMO](https://bilibili.github.io/WebAV/demo/4_1-recorder-usermedia#%E4%BF%AE%E5%A4%8D%E8%BE%93%E5%87%BA%E6%96%87%E4%BB%B6%E4%B8%8D%E6%98%BE%E7%A4%BA%E6%97%B6%E9%95%BF)
> 
> _This project has changed organizations, so the domain has changed._

Thank you 👍
