### ISSUE TITLE
可以支持录制某个非Canvas元素为mp4视频么

### ISSUE THREAD

**Issue by wangller** [hughfenghen/WebAV#21]
请教一下大佬，webav能解决下面的问题么
![image](https://github.com/hughfenghen/WebAV/assets/24286937/4243808c-b87f-473c-904f-30c4e628883e)
1. 这是一个图片播放器，是一个div元素包含了图片，select等元素，需要录制成视频
2. 但是WebCodecs API貌似支持录制canvas元素或者整个窗口
3. 现在是先html2canvas，再用Whammy生成webm，但视频清晰度会比较低

**Comment by hughfenghen** [comment]
@wangller 
如果你能有分享屏幕权限，可以考虑分享屏幕，绘制到canvas之前，裁剪掉你不想要的内容，然后录制 canvas。

另外，
如果你要输出WebM视频格式的视频，现在只需要 MediaRecorder API 不需要其它第三方库
如果你要输出 mp4 可以 @webav/av-recorder
两个方法需要的参数都是 canvas
