### ISSUE TITLE
可以添加暂停录制和恢复录制功能吗？

### ISSUE THREAD

**Issue by jiewuxiaozi2009** [hughfenghen/WebAV#22]

**Comment by hughfenghen** [comment]
@jiewuxiaozi2009 
可以考虑，[bloom-shadow](https://github.com/hughfenghen/bloom-shadow/blob/main/src/avcanvas.ts#L78) 项目已经实现了暂停、恢复功能

我需要把它集成到 AVRecorder 中

**Comment by hughfenghen** [comment]
```js
// pause recording
recorder.paused = true
// resume recording
recorder.paused = false
```
@jiewuxiaozi2009  
v0.2.1 支持暂停/恢复录制功能了

体验 [DEMO](https://hughfenghen.github.io/WebAV/demo/record-usermedia.html)

**Comment by hughfenghen** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/MediaRecorder  
也有 暂停/恢复 功能，应该参考 MediaRecorder 实现 API，减少学习成本

**Comment by hughfenghen** [comment]
v0.2.3
```js
recorder.pause()
recorder.resume()
```
