### ISSUE TITLE
@webav/av-cliper 如何循环的解码mp4

### ISSUE THREAD

**Issue by alexhaifeng** [hughfenghen/WebAV#23]
目前看demo是只解码一次

**Comment by alexhaifeng** [comment]
[Discord](https://discord.gg/ePvff7a6) 的邀请已经失效了，请问有什么渠道可以实时交流，谢谢

**Comment by hughfenghen** [comment]
@alexhaifeng  邀请链接已更新

你可以参考 https://hughfenghen.github.io/posts/2023/07/23/webav-2-parse-video/#webav-%E8%A7%86%E9%A2%91%E8%A7%A3%E6%9E%90%E7%A4%BA%E4%BE%8B
读取 mp4 的视频帧

解码过程是自动，前提是必须先消耗前面产生的视频帧（close VideoFrame），所以你需要循环读取（tick）帧，处理完 close 它。

如果目前API不能满足你的需求，请介绍你诉求背景和期望。

**Comment by alexhaifeng** [comment]
目前，播放完毕一轮，就会停止播放了。如果要重新播放，就需要重新解码，再次播放，是这样吗？


> @alexhaifeng 邀请链接已更新
> 
> 你可以参考 https://hughfenghen.github.io/posts/2023/07/23/webav-2-parse-video/#webav-%E8%A7%86%E9%A2%91%E8%A7%A3%E6%9E%90%E7%A4%BA%E4%BE%8B 读取 mp4 的视频帧
> 
> 解码过程是自动，前提是必须先消耗前面产生的视频帧（close VideoFrame），所以你需要循环读取（tick）帧，处理完 close 它。
> 
> 如果目前API不能满足你的需求，请介绍你诉求背景和期望。

**Comment by hughfenghen** [comment]
是的

**Comment by alexhaifeng** [comment]
在worker里执行，内部不会延时，需要在外部调用sleep
![image](https://github.com/hughfenghen/WebAV/assets/39294000/03b903f3-098b-4d3b-af2c-f771408fd46c)

**Comment by hughfenghen** [comment]
这个示例是为了演示 快速解码视频文件，获得视频帧。

你如果要希望获得正常速度播放时的视频帧有好几个其他方法，不一定要使用  av-cliper 的
