### ISSUE TITLE
AVCanvas录制视频无数据输出

### ISSUE THREAD

**Issue by a114711074** [hughfenghen/WebAV#26]
https://hughfenghen.github.io/WebAV/demo/record-avcanvas.html

demo录制mp4无数据输出，

Win11平台 
Chrome  117.0.5938.150

**Comment by hughfenghen** [comment]
原因是 AVCanvas.captureStream 方法执行时 `this.spriteManager.audioCtx.state === 'suspended'`；
此时返回的 MediaStream 音轨无数据输出
