### ISSUE TITLE
提取视频给定时间点上的一帧图片

### ISSUE THREAD

**Issue by endink** [hughfenghen/WebAV#27]
如题

**Comment by hughfenghen** [comment]
你的意思是，使用时间参数从视频文件中提取视频帧么？

**Comment by endink** [comment]
是的，通过时间或者通过传入帧索引，第 X 帧图片，可能传帧索引参数会通用一点，因为用户可以自己根据 FPS 和时间计算是第几帧

**Comment by gxmari007** [comment]
感觉你说的是clip实例的tick方法

**Comment by hughfenghen** [comment]
tick 能用时间取到帧，但需要全量解码视频，过程会很慢。
如果目的只是取10分钟视频的最后一帧，tick就很浪费资源。

可以跳过前面编码数据块，只解码对应的 chunk 就会快很多。

**Comment by hughfenghen** [comment]
使用 mp4box 解封装，找到对应 chunk 使用 VideoDecoder 解码，实现起来其实比较简单。

你可以参考 webav 项目的 mp4-utils 代码实现（欢迎PR），或等我开放一个工具函数。

**Comment by endink** [comment]
谢谢指教

**Comment by endink** [comment]
其实是为了做出 timeline , 一次提取多个帧用哪个方案最快

**Comment by endink** [comment]
timeline 中预览帧画面是所有视频编辑软件的基础功能，既然这个项目是工具向，是否可以提供这个功能？输入需要预览的数量，平均的得到帧，例如输入3 ，得到第一帧，中间帧，最后一帧，类推输入4,5....n, 视频等分成 n - 1 段，获取头尾和相邻片段之间的帧

**Comment by hughfenghen** [comment]
如果是为了实现预览图功能，实现方式又不一样了。
预览图一般是取关键帧，将关键帧转换成图片保存在本地或者内存。

**Comment by endink** [comment]
关键帧？视频帧还有关健和非关键的区别？这个需求就是为了时间轴帧预览的，不加载全部视频的情况下快速提取时间轴上的帧

**Comment by endink** [comment]
至于保存还是直接 render 到 canvas 那是开发者的自由了，但是如果这个库能提供提取帧就很酷

**Comment by hughfenghen** [comment]
> 至于保存还是直接 render 到 canvas 那是开发者的自由了，但是如果这个库能提供提取帧就很酷

实际情况做不到这么么自由的，比如Chrome最多存在16给帧对象，因为帧对象非常占用显存。
所以要对场景做一些限定。

**Comment by endink** [comment]
前端不是太熟，如果这在后端做事非常容易的，就是不要想耗费服务器内存了，另外 safari 是否可以兼容，MAC占比也很高

**Comment by hughfenghen** [comment]
高版本 Safari 16.4+ 部分功能支持，没验证具体支持到什么程度

**Comment by GreenChang01** [comment]
感觉你这个seek应该不太容易实现把
开始的时候已经将所有的sample都加入了解码器
后续的seek要么记录最后已解码的位置->flush->加入seek到的sample
要么搞一个新的解码器->加入seek到的sample

> 使用 mp4box 解封装，找到对应 chunk 使用 VideoDecoder 解码，实现起来其实比较简单。
> 
> 你可以参考 webav 项目的 mp4-utils 代码实现（欢迎PR），或等我开放一个工具函数。

**Comment by hughfenghen** [comment]
> 开始的时候已经将所有的sample都加入了解码器

如果能想实现 seek 就不需要把所有 Sample 传入解码器， 只需要给指定的 Sample
如果当前 Sample 不是关键帧，则往前找关键帧，确保第一个传入解码器的是关键帧就行

seek 跟解码器无关，seek 是由容器解封装层来实现的。

**Comment by GreenChang01** [comment]
我是想表达如果要加入seek有点麻烦
比如代码中demuxcode在onChunk的时候已经将所有的sample加入了解码器
此时如果拖动进度条(比如视频剪辑的时候),会经常seek,相当于每次拖动都要将解码器reset再重新加入seek到的关键帧sample到视频的结束这么多的samples加入解码器

> > 开始的时候已经将所有的sample都加入了解码器
> 
> 如果能想实现 seek 就不需要把所有 Sample 传入解码器， 只需要给指定的 Sample 如果 seek 后找到的 Sample 不是关键帧，则往前找关键帧，确保第一个传入解码器的是关键帧就行
> 
> seek 跟解码器无关，seek 是由容器解封装层来实现的。

**Comment by GreenChang01** [comment]
> > 开始的时候已经将所有的sample都加入了解码器
> 
> 如果能想实现 seek 就不需要把所有 Sample 传入解码器， 只需要给指定的 Sample 如果 seek 后找到的 Sample 不是关键帧，则往前找关键帧，确保第一个传入解码器的是关键帧就行
> 
> seek 跟解码器无关，seek 是由容器解封装层来实现的。

mp4box.js的seek方法似乎有问题, 传入的时间是正确的 但是返回的offset则不正确
好像只要之前的samples被消费过了就直接跳过了

**Comment by hughfenghen** [comment]
如果需要频繁 seek 获取对应时间的图像帧，实现思路：
将 mp4 文件解码后得到 samples 存储到本地文件（OPFS API），同时存好 索引文件（时间-sample 映射关系）
然后根据时间去读本地文件（OPFS API）得到 sample， 传给 WebCodecs  就能解码得到图像，实现快速 seek

如果给定时间取得的 sample-A 不是**关键帧**，  应该反向找到最近的第一个关键帧，**先解码关键帧，再解码 sample-A**

**Comment by endink** [comment]
这个问题似乎没有答案了，已经改用 webassembly（ffmpeg）实现了，请教一下作者，关键帧距离要抽帧的时间点很远时候抽帧就很慢，如何改善？mov 得到的可能是 YUV422,如何渲染？

**Comment by hughfenghen** [comment]
正在尝试实现，大概两个星期。
着急可以参考前文的思路先实现，欢迎 pr。

我对 ffmpeg 不熟。

**Comment by endink** [comment]
感谢回复，请教一下 mov 如何支持？自己解码得到 YUV 帧是否有可能播放？

**Comment by hughfenghen** [comment]
v0.3.0 实现了 `MP4Previewer`

API： https://hughfenghen.github.io/WebAV/_api/av-cliper/classes/MP4Previewer.html
DEMO： https://hughfenghen.github.io/WebAV/demo/1_4-mp4-previewer

**Comment by hughfenghen** [comment]
[v0.4.0](https://github.com/hughfenghen/WebAV/pull/66)
废弃 MP4Previewer；v1.0 将删除该该 API
迁移方法：使用 `MP4CLip.tick` 替代 `MP4Previewer.preview`
