### ISSUE TITLE
MP4Clip能否导出完整的音频pcm数据

### ISSUE THREAD

**Issue by alexhaifeng** [hughfenghen/WebAV#28]
我们的场景：
下载到完整的mp4资源，用mp4clip解码出音视频， 
video 切片播放就行，
音频获取到完整的pcm数据直接播放更加流畅简洁

**Comment by alexhaifeng** [comment]
我们希望在worker里实现播放video, 把完整的audio pcm发送到主线程，播放音频

**Comment by hughfenghen** [comment]
MP4Clip 无法一次性获取音轨的所有 PCM，因为解码是流式的；
前面的数据没有消费掉（close），就无法获取到后面的数据

**Comment by hughfenghen** [comment]
浏览器最多同时存在一定数量的 VideoFrame 对象（chrome 大概是 16 个），避免显存溢出。
必须消费掉（close）已有的 VideoFrame 对象，才会有新的 VideoFrame 对象；
视频解码卡住，也会阻塞音频解码。

所以无法一次性获取所有 PCM 数据。

**Comment by hughfenghen** [comment]
优化了 demo 中使用 AudioContext 播放 PCM 的效果，现在能流畅播放，不会有卡顿现象了

https://github.com/hughfenghen/WebAV/blob/42ff7cf01799e9329836551d88058ffbda8f4c06/packages/av-cliper/demo/decode-media.ts#L78

**Comment by chenzhutian** [comment]
hello, 我也有这样的需求, 想知道怎么才能获取一大段的pcm, 而不仅仅是一帧的. 
根据demo, 对每一帧音频都要创建一个bufferSource (`ctx.createBufferSource()`) 然后再connect到ctx上. 我发现这样在性能一般的机子上会导致卡顿 (我暂时也不知道为啥)
我想尝试把所有帧合并成一个bufferSource然后试试, 暂时没找到方法. 不知道作者能否提供一些启发

**Comment by hughfenghen** [comment]
一定要完整 PCM 的话， 可以按时间顺序调用 tick，将所有 PCM 数据（类型 [Float32Array, Float32Array]）提取出来，然后合并成一个大的 PCM。

另外，可以参考 [splitTrack DEMO](https://hughfenghen.github.io/WebAV/demo/6_3-split-track) 提取音轨，
`Combinator.add(audioTrackClip)` 然后 ouput 生成一个 m4a 文件，用于提取音频播放

**Comment by chenzhutian** [comment]
最终我在这里看到了别人的讨论: https://github.com/katspaugh/wavesurfer.js/discussions/2762
大意是说用BufferSourceNode播放大段音频容易内存泄漏而且很吃计算资源, 建议用HTMLAudioElement来播放

于是我现在采用的解决方案是:
1. 编辑器播放audio采用HTMLAudioElement
2. 编码/合成音频用WebAV
3. 
于是等于没用上WebAudio的API来
