### ISSUE TITLE
播放的速率如何控制

### ISSUE THREAD

**Issue by GreenChang01** [hughfenghen/WebAV#29]
HI 我想问下av-cliper中decode-media.html的播放速率如何控制 

`// 最快速度渲染视频所有帧
while (true) {
  const { state, video: videoFrame } = await clip.tick(time)
  if (state === 'done') break
  if (videoFrame != null && state === 'success') {
    ctx.clearRect(0, 0, cvs.width, cvs.height)
    // 绘制到 Canvas
    ctx.drawImage(videoFrame, 0, 0, videoFrame.codedWidth, videoFrame.codedHeight)
    // 注意，用完立即 close
    videoFrame.close()
  }
  // 时间单位是 微秒，所以差不多每秒取 30 帧，丢掉多余的帧
  time += 33000
}
clip.destroy()`
这里你提到了时间单位是 微秒，所以差不多每秒取 30 帧，丢掉多余的帧
如果我只是想按照正常速度播放这个视频 这里的time应该取多少 或者有什么公式来计算
如果我想要按照可变速率来播放视频，又要增加什么参数呢

**Comment by hughfenghen** [comment]
更新了 DEMO，可选择解码速度，https://hughfenghen.github.io/WebAV/demo/decode-media.html
![image](https://github.com/hughfenghen/WebAV/assets/3307051/4bbd70e7-a26b-4beb-8948-3f8d59c2e3d9)

正常速度解码代码
```js
let startTime = performance.now()

const timer = setInterval(async () => {
const { state, video } = await clip.tick(
  // x1 表示正常速度
  Math.round((performance.now() - startTime) * 1000) * 1
)
if (state === 'done') {
  clearInterval(timer)
  clip.destroy()
  return
}
if (video != null && state === 'success') {
  ctx.clearRect(0, 0, cvs.width, cvs.height)
  ctx.drawImage(video, 0, 0, video.codedWidth, video.codedHeight)
  video.close()
}
}, 1000 / 30)
```

主要是通过控制 `clip.tick` 的参数实现，如果你想3 倍速播放
`Math.round((performance.now() - startTime) * 1000) * 3`

**Comment by hughfenghen** [comment]
重新优化了 DEMO，可选择解码（0.5、1、3）倍速，https://hughfenghen.github.io/WebAV/demo/decode-media.html

源码位置：https://github.com/hughfenghen/WebAV/blob/fe2f76be82fb8c2272a9f12d49df31b8f26a346c/packages/av-cliper/demo/decode-media.ts#L150
