### ISSUE TITLE
chrome和electron偶现dec reclaimed due to inactivity.

### ISSUE THREAD

**Issue by a114711074** [hughfenghen/WebAV#31]
长时间（>5分钟）录制偶现dec reclaimed due to inactivity.提示，后续调用encode失败，无法录制，未能找到出现规律。
可能限制电脑一段时间会出现（未息屏）

**Comment by hughfenghen** [comment]
@a114711074 
请提供更详细的信息：
1. 操作系统、浏览器及版本
2. WebAV 的版本，能复现问题的核心代码，或 DEMO 链接
3. 录制生成的文件是否能播放，占用了多少空间？

**Comment by hughfenghen** [comment]
可能跟 #25 是同一个问题，提供详细信息  或确认录制的非静态画面（非 #25）再重开当前 issue
