### ISSUE TITLE
您好，可以通过将VideoFrame mux成 fmp4 喂给MSE播放的功能吗？

### ISSUE THREAD

**Issue by huotong1212** [hughfenghen/WebAV#33]
目前只看到了合成完整的mp4的功能，以及再canvas上展示的这样的功能。

**Comment by hughfenghen** [comment]
可以的，这里有 demo：https://github.com/hughfenghen/wcm-recoder
> canvas captureStream -> MediaStreamTrackProcessor.readable -> mp4box.js + webcodecs (run in webworker) -> ReadableStream(mp4 ArrayBuffer, can be pushed to server) -> mp4box.js -> Segment ArrayBuffer -> video element + MSE

`MediaStreamTrackProcessor.readable` 输出的就是 `VideoFrame`，最终得到的 `Segment ArrayBuffer` 就是 MSE 需要的数据
