### ISSUE TITLE
基于canvas来生成mp4能否有更快速的解决方案

### ISSUE THREAD

**Issue by athlan20** [hughfenghen/WebAV#38]
目前手头有个项目需要模仿类似剪映，腾讯智影等在线视频编辑，实现一个简易版在线视频编辑项目，要求是“纯前端“。
仓库项目中类似av-canvas的功能，但是目前av-canvas最终导出mp4的时候，需要从头到尾播放一遍，这个有些慢了，作者能否有快速一些导出mp4的方案实现

**Comment by hughfenghen** [comment]
https://github.com/hughfenghen/WebAV/blob/65ae77c/packages/av-cliper/src/clips/img-clip.ts#L5
可以参考 img-clip 实现一个 canvas clip  的  tick (time: number) 方法

根据 time，在 canvas 上绘制内容，每次绘制创建一个新的 VideoFrame 然后返回
要求使用者知道 canvas 某个时刻，应该绘制什么内容

**Comment by hughfenghen** [comment]
@athlan20 
https://hughfenghen.github.io/WebAV/demo/2_6-custom-clip

写了一个 DEMO，演示 canvas 快速导出视频的原理

**Comment by athlan20** [comment]
哇~~多谢大佬啊~
