### ISSUE TITLE
fastConcatMp4方法会丢失mp4a内的esds

### ISSUE THREAD

**Issue by shark4514css** [hughfenghen/WebAV#40]
<img width="551" alt="image" src="https://github.com/hughfenghen/WebAV/assets/20633913/03b00bed-8940-462a-a954-d9090c09eddb">
以上是合成后
<img width="512" alt="image" src="https://github.com/hughfenghen/WebAV/assets/20633913/afd1d8e9-7717-48eb-a60e-004b05e04ad6">
以上是正确视频编码截图

这个问题会导致在windows上的media player播放器播放失败

**Comment by hughfenghen** [comment]
@webav/av-cliper@0.2.15
已修复
