### ISSUE TITLE
.mov 本地文件编辑，播放支持

### ISSUE THREAD

**Issue by endink** [hughfenghen/WebAV#43]
是否可以支持 mov,苹果设备很多

**Comment by hughfenghen** [comment]
待定，有不小的工作量，先观察多少人有这个诉求。（欢迎 PR）

在 WebAV 支持 mov 格式之前，可以考虑先用 ffmpeg 转封装为 mp4。

**Comment by endink** [comment]
Webassembly ffmepg 解码 mov 实在实在太慢了

**Comment by hughfenghen** [comment]
wasm 解码很慢，转封装速度还行。

**Comment by endink** [comment]
能否提供一下 mov （本地文件 File）解码的思路，感谢

**Comment by BOKE2014** [comment]
> 待定，有不小的工作量，先观察多少人有这个诉求。（欢迎 PR）
> 
> 在 WebAV 支持 mov 格式之前，可以考虑先用 ffmpeg 转封装为 mp4。

MOV非常重要，大佬不能少了兼顾这个生态系统。

**Comment by 027xiguapi** [comment]
建议增加支持 webm 的解析

**Comment by hughfenghen** [comment]
@BOKE2014 @endink   
MOV 与 MP4 类似，可以使用 mp4box.js 解封装，所以 MP4Clip 支持输入 mov 格式的视频
`new MP4Clip((await fetch('xxx.mov')).body)` 即可

**Comment by endink** [comment]
最新的苹果设备会默认使用 hevc 编码，ffmepg 解码也很慢，似乎没有太好的办法

**Comment by hughfenghen** [comment]
WebAV 使用 WebCodeccs 解码，如果设备支持，默认会选择硬解的，速度应该还行。

WebAV 的目的之一就是提升中浏览器中解码速度的，FFmpeg 慢是因为不能在浏览器中硬解视频。

**Comment by endink** [comment]
目前桌面浏览器 HEVC 需要手动开启，用户不会弄，因为音视频不是太熟悉，请问一下，ffmpeg 中的 packet 是否有办法直接传递给 WebAV， 这样可以兼容很多格式（比如 webm），其实慢是 read frame, read packet 速度还行，就是解码时候用 WebAV 利用 GPU, 解封装时候用 ffmpeg 兼容更多格式

**Comment by hughfenghen** [comment]
> 建议增加支持 webm 的解析

待定，建议创建新 issue 跟进
最好描述下场景，你们的 webm 视频文件怎么产生的，为什么要使用这个格式？
我个人使用 webm 格式的视频相对较少。
