### ISSUE TITLE
这将是一个非常先进和有用的项目，但我如何将项目转换为js在浏览器中运行呢？

### ISSUE THREAD

**Issue by Xikee2023** [hughfenghen/WebAV#45]
作者你好，感谢你的贡献，这是一个非常超前的项目，我简单地尝试过WebCodecs API的性能，它的性能不是wasm可比的，相信您的项目能解决许多问题。
我想提一个可能很愚蠢的问题，您的这个用ts编写的项目如何打包为js项目，以在浏览器中运行呢？（我从来没有接触过ts开发）。
例如我希望使用贵项目中的“fastConcatMP4”模块，我应该如何将它导出为js呢？

**Comment by hughfenghen** [comment]
fastConcatMP4 不是一个通用的用来拼接视频的工具函数，主要配合 Combinator 实现  实现合成拼接的

如果要拼接非 Combinator 输出的视频流，视频资源格式、编码、分辨率 等参数都是一致的情况，可以试试

1. 安装npm依赖 @webav/av-cliper
2. 体验 [DEMO](https://hughfenghen.github.io/WebAV/demo/2_5-video-compsite-and-concat)，阅读 DEMO 的源码
3. 对照 DEMO  源码，使用 fastConcatMP4 拼接视频
