### ISSUE TITLE
IOS端绿幕抠除，无法显示

### ISSUE THREAD

**Issue by liuemmm** [hughfenghen/WebAV#46]
Safari报错Unhandled Promise Rejection: Error: Cant create gl context

**Comment by hughfenghen** [comment]
@webav/av-cliper@0.3.2 修复了

Safari OffscreenCanvas  不支持 webgl2

<img width="724" alt="image" src="https://github.com/hughfenghen/WebAV/assets/3307051/bac5f3c0-d87a-4b46-8edf-38b006da1d80">
