### ISSUE TITLE
两个mp4视频拼接时出现错误

### ISSUE THREAD

**Issue by Xikee2023** [hughfenghen/WebAV#47]
经过简单测试，这是一个很棒的项目！速度超快！
但我在拼接某两个mp4文件时，发生错误，给作者反馈一下，以便能更好地完善这个优秀的项目。
以下是我的示例代码：
html
`<video id="video" controls></video>`

javascript

```
import {
    MP4Clip,
    ImgClip,
    createChromakey,
    Combinator,
    OffscreenSprite,
    fastConcatMP4,
} from '@webav/av-cliper';
const videoList = [
    'https://aisort.net/video/f1.mp4',
    'https://aisort.net/video/f2.mp4'
];
const width = 1920;
const height = 720;
async function start() {
    const coms = (await Promise.all(videoList.map(async (vurl) => (await fetch(vurl)).body)))
        .map((sbody) => {
            return new MP4Clip(sbody);
        })
        .map((clip, idx) => new OffscreenSprite(`spr${idx}`, clip))
        .map(async (spr, idx) => {
            const com = new Combinator({ width, height });
            await spr.ready;
            //spr.rect.x = idx * spr.rect.w;
            spr.rect.x = 0;
            //await com.add(imgSpr);
            await com.add(spr, { main: true });
            return com.output();
        });
    return await fastConcatMP4(coms);
}
start().then(async res => {
    const buffer = await new Response(res).arrayBuffer();
    const blob = new Blob([new Uint8Array(buffer)], {type: 'video/mp4'})
    const video = document.getElementById('video');
    video.src = URL.createObjectURL(blob);
});
```

错误截图：
![image](https://github.com/hughfenghen/WebAV/assets/138852790/7deffc21-622e-4ee8-8e89-ecc8c0dd2289)

这可能是由于视频编码导致的问题吗？如尝试使用demo中的 123.mp4、223.mp4、323.mp4 视频进行拼接，它是可以跑通的，但换了其它视频，就跑不通了。

**Comment by hughfenghen** [comment]
提供一下原始视频 f1、f2

**Comment by hughfenghen** [comment]
最好把文件下载到本地，有可能是网络原因，不翻墙无法访问你给的视频资源

下载到本地是 ok 的。
<img width="908" alt="image" src="https://github.com/hughfenghen/WebAV/assets/3307051/4a1b4b63-cf1e-4ea4-9b72-ff563040d29b">
<img width="1189" alt="image" src="https://github.com/hughfenghen/WebAV/assets/3307051/dfb4c8ba-1864-4036-9b7d-b726a2db3a11">

**Comment by Xikee2023** [comment]
我就是在本地测试的，我将视频上传到服务器是方便您下载测试。直接fetch后将response.body通过 fast contact mp4 直接拼接是没有问题的，我也测试成功了(如果视频的时间戳不同，直接使用fast contact mp4会出错)，但通过Combinator新建视频后再拼接(像我提供的代码那样)，就不行了。您可以测试一下。

**Comment by hughfenghen** [comment]
请使用**官方项目的 demo** 在本地测试，提供一个可复现的路径或代码。

同时 尝试下其他设备，检查是否某个设备的兼容性。
了解视频编码格式，你的机器是否支持。

**Comment by hughfenghen** [comment]
视频编码格式是  avc1.640028
建议在浏览器控制台中执行 `await VideoDecoder.isConfigSupported({codec: 'avc1.640028'})`，确认设备支持解码当前格式

我先关闭这个 issue，如果确认是 项目的 bug（排除了设备兼容性或自身代码的bug），再从新打开
