### ISSUE TITLE
添加的素材只保留原比例缩放

### ISSUE THREAD

**Issue by BOKE2014** [hughfenghen/WebAV#48]
大佬能不能将插入的素材，如：video，image和text只保留按原比例缩放。因为一不小心比例变了弄不回去只能删了再添加。

谢谢！

**Comment by hughfenghen** [comment]
建议在业务层支持一个“重置”功能，用户点击时将素材重置为初始状态（宽高）

**Comment by hughfenghen** [comment]
“重置” 功能将列入诉求收集，决定实现优先级

**Comment by pbdm** [comment]
和重置不是一个事情，还是期望优先搞下

**Comment by hughfenghen** [comment]
next 版本（0.9.0-beta.16） 已支持

`sprite.rect.rect.fixedAspectRatio = true` 将移除四个控制点，只能等比例缩放

<img width="331" alt="image" src="https://github.com/hughfenghen/WebAV/assets/3307051/0ac7907a-ea8b-4687-bf60-8886fef2a351">
