### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by onthegit** [hughfenghen/WebAV#5]
Hello,
thanks for the project.
After some testing I noticed that memory is increasing in chrome (without being gced). I suspect it is because releaseUsedSamples is not being called and all the the chunks stay in mp4boxjs.
More info here:
https://github.com/gpac/mp4box.js/wiki/Memory-managment-in-MP4Box.js

**Comment by hughfenghen** [comment]
Yeah, it's true that mp4 samples are not being actively released at the moment, and processing larger video files may have memory leak.

I expect to submit the memory optimization code next week.

**Comment by hughfenghen** [comment]
@onthegit 
The GPU memory overload issue has been resolved and the js heap is currently increasing slowly but not significantly.
I will close this issue and if it does not resolve the issue you are experiencing, please reopen the issue and provide the test file.
