### ISSUE TITLE
视频解析时长为 0，导致无法预览图片

### ISSUE THREAD

**Issue by 027xiguapi** [hughfenghen/WebAV#53]
https://github.com/hughfenghen/WebAV/assets/31228055/a756dbf5-c285-4b2b-aaa0-daadfbdccdf6

![ac5ccd768fe294e341b0d79f15ba3ea](https://github.com/hughfenghen/WebAV/assets/31228055/dfe9e4d5-bfc2-41bd-93e3-8208d9b71216)
如图 视频信息的 duration 为 0

![image](https://github.com/hughfenghen/WebAV/assets/3307051/5587aace-351d-408a-a76d-b33708c8f2c8)
duration 为 0，无法显示时长和预览图片
https://hughfenghen.github.io/WebAV/demo/1_4-mp4-previewer

**Comment by hughfenghen** [comment]
> 用 @webav/av-recorder 录制的视频 也会出现同样的问题

@027xiguapi   参考 https://github.com/hughfenghen/WebAV/issues/20

**Comment by 027xiguapi** [comment]
![image](https://github.com/hughfenghen/WebAV/assets/31228055/3307e9ac-6e41-4cbb-90fd-9659a5907b62)
如果无法获取时长，就无法获取到关键帧，为了可以获取，我修改了源码
```
if (info.duration != 0 && time > info.duration / info.timescale)
      return null;
```

建议可以加上时长设置

**Comment by hughfenghen** [comment]
![image](https://github.com/hughfenghen/WebAV/assets/3307051/40a59b8f-e7af-495e-96ed-d5ee9e3af6f5)
问题在于，程序实际使用的是 videoTrack 下的 duration 字段，你期望的是 movie_duration 字段。

**Comment by hughfenghen** [comment]
会在下个版本修复，将由最后一个 sample 决定时长，而不是从 moov 中读取时长信息

**Comment by hughfenghen** [comment]
> 会在下个版本修复，将由最后一个 sample 决定时长，而不是从 moov 中读取时长信息

v0.4.0 已发布，查看 demo：https://hughfenghen.github.io/WebAV/demo/6_2-video-preview-cut
有问题再重开

**Comment by DeanDai** [comment]
> > 会在下个版本修复，将由最后一个 sample 决定时长，而不是从 moov 中读取时长信息
> 
> v0.4.0 已发布，查看 demo：https://hughfenghen.github.io/WebAV/demo/6_2-video-preview-cut 有问题再重开

Hi, seems like the demo is unavailable, may I know how to solve the issue? Thanks
