### ISSUE TITLE
请教下：webav的录制保存视频API是否可以和已有canvas衔接？

### ISSUE THREAD

**Issue by xeoshow** [hughfenghen/WebAV#56]
请教下：就是我们自己已经写好我们自己的canvas逻辑和代码了(用fabric，也支持视频等动画)，是否可以直接衔接上webav的录制保存视频API呢？谢谢

**Comment by hughfenghen** [comment]
已支持

> 使用 AVRecorder 可以录制 AVCanvas，输出 MP4 文件；AVCanvas 添加音频素材，输出的视频文件就会包含音轨。
> 你也可以使用原生 canvas 或第三方库（如 fabric.js）绘制图像内容，然后录制从 canvas 捕获的流，new AVRecorder(canvas.captureStream())。

https://hughfenghen.github.io/WebAV/demo/4_2-recorder-avcanvas

**Comment by hughfenghen** [comment]
如果要录制非实时内容，快速生成视频，精确控制每一个时刻、每一帧的内容
请参考：https://hughfenghen.github.io/WebAV/demo/2_6-custom-clip
