### ISSUE TITLE
从视频素材中拆分出独立的音频轨道素材

### ISSUE THREAD

**Issue by Reinhard2019** [hughfenghen/WebAV#57]
场景：想要实现和剪影一样的从视频文件中分离音频流的功能
![image](https://github.com/hughfenghen/WebAV/assets/13881726/f3f905c2-8569-4f3c-a78e-548064f4975a)
期望：从任意存在音频流的视频文件分离音频流

**Comment by hughfenghen** [comment]
同意支持该功能，会在 feat/cut 分支实现，下个 minor 版本发布
