### ISSUE TITLE
IClip的 async tick(time: number)，默认周期是多少？可以自己自定义吗？

### ISSUE THREAD

**Issue by xeoshow** [hughfenghen/WebAV#58]
如题
https://hughfenghen.github.io/WebAV/_api/av-cliper/interfaces/IClip.html#tick
![779d5a030e99c653f276ef929665e4f](https://github.com/hughfenghen/WebAV/assets/1164284/74c3aaa9-f41d-4c34-b5c3-b8f4867a0974)

**Comment by hughfenghen** [comment]
`tick` 是 `IClip` 接口的公开方法
1. 如果你直接使用 Clip（比如解码素材 渲染），时间周期由调用者自行控制
    - 多次调用 `MP4Clip.tick` 最好维持一定频率，否则可能会影响性能
2. 如果你使用 `Combinator` 合成视频，Combinator 固定以 **30FPS** 频率调用素材（Clip）的 `tick` 方法，大概 33ms 一次
    - 如果有诉求设置视频的 FPS，可另外提需求

**Comment by xeoshow** [comment]
最好可以周期时间更小的颗粒度，因为小颗粒度到粗颗粒度，可以在里面等待一帧就行，但粗颗粒度无法到小颗粒度...
大部分时候还是有60帧率的诉求？

**Comment by xeoshow** [comment]
或者最好可以外部有某个API，可以初始化设置该周期

**Comment by xeoshow** [comment]
我们在尝试和我们已有canvas逻辑整合，我们自己canvas代码里也有ticker逻辑，大概如下所示。尝试了好几天，我们ticker和IClip的 async tick(time: number)，整合非常非常困难。
是否有可能，IClip的ticker，直接就用我们自己那个ticker进去呢？
```
app.ticker.add((delta) => {
  // 每次渲染完成时会触发该回调，delta时间值并不恒定，是为了保持对不同性能设备都有良好的顺畅度
  ......
});
```

**Comment by hughfenghen** [comment]
经沟通未能理解上下文

**Comment by xeoshow** [comment]
这个问题也可以参看这个后续的单开的issue:
https://github.com/hughfenghen/WebAV/issues/75
