### ISSUE TITLE
webCodecs如何对接h264的裸流数据

### ISSUE THREAD

**Issue by Doris0812** [hughfenghen/WebAV#59]

**Comment by hughfenghen** [comment]
WebCodecs VideoDecoder 解码的数据类型为 EncodedVideoChunk
EncodedVideoChunk 是有一个或多个 H264 的 NALU 组成的

所以，要解码 H264 裸流，
1. 需要先判断裸流是 AVCC 还是 AnnexB 格式，
2. 提取配置 初始化 VideoDecoder 实例
3. 提取 NALU 的二进制数据，包装为 EncodedVideoChunk
4. 调用 VideoDecoder.decode 进行解码

参考：https://github.com/dreamsxin/example/blob/master/codec/H.264视频码流解析.md
