### ISSUE TITLE
咨询问题，在vue3中，调用MP4Clip类的tick方法，报错Uncaught (in promise) TypeError: Cannot read from private field

### ISSUE THREAD

**Issue by my76572** [hughfenghen/WebAV#61]
![431711626708_ pic_hd](https://github.com/hughfenghen/WebAV/assets/23089731/bbf3aa31-b823-4095-b0c6-f6d225c8b4b5)

**Comment by hughfenghen** [comment]
请截图错误堆栈对应的代码
![image](https://github.com/hughfenghen/WebAV/assets/3307051/ab2143e8-bfe2-4a70-8347-633ad9f7d1ce)

**Comment by my76572** [comment]
<img width="1173" alt="image" src="https://github.com/hughfenghen/WebAV/assets/23089731/c20db5ec-ecf7-42ef-bd7e-d7632857c301">

**Comment by my76572** [comment]
代码已粘贴，麻烦博主有空看一下

**Comment by hughfenghen** [comment]
看不出问题，请提供最小化可复现仓库

**Comment by my76572** [comment]
代码地址git clone https://gitee.com/solve_847/webav_test.git，详情见readme.md

**Comment by hughfenghen** [comment]
![image](https://github.com/hughfenghen/WebAV/assets/3307051/7771a124-e8a4-47c9-9e19-a3f687c1c708)

不要将 clip 挂在在 Vue 的 data 下，Vue 会 Proxy data 下的所有字段
