### ISSUE TITLE
咨询问题： 需求: 在一段时长为30秒的视频中，截取10秒到20秒之间的视频内容，并存储为新的视频mp4，这个功能该怎么操作

### ISSUE THREAD

**Issue by my76572** [hughfenghen/WebAV#62]
在feat cut 分支的中，看到的demo是删除整段视频中的某个视频，用deleteRange方法来实现。如果是保留某短视频内容该怎么实现，该浏览哪些文档

**Comment by hughfenghen** [comment]
裁剪前后，剩下的就是中间片段
假设视频 30s
1.  丢弃前 10s deleteRange(0, 10e6)
2. 丢弃后 10s deleteRange(10e6, 20e6)

剩下的就是原视频的中间 10s
