### ISSUE TITLE
0.4.0版本的avclip在tick 0的时候没有video（图像帧）返回

### ISSUE THREAD

**Issue by athlan20** [hughfenghen/WebAV#67]
0.4.0版本在tick 0的时候没有video返回，之前0.3.3是有的，期待老大一个骚操作~

**Comment by hughfenghen** [comment]
因为视频第一帧的时间大于 0，所以取不到帧
0.3.3 解析 MP4 的时候，为了避免第一帧黑屏有个骚操作， 在 0.4.0 被移除了
如果不想要前面的黑屏帧，现在可用新的 API MP4Clip.deleteRange 移除前面的黑屏时间

0.4.0 更新详情请看：https://github.com/hughfenghen/WebAV/pull/66
