### ISSUE TITLE
某些 MP4 资源合成进度暂停，无法获取到合成视频流

### ISSUE THREAD

**Issue by teyra** [hughfenghen/WebAV#71]
DEMO 资源合成正常，下面的资源合成时，进度暂停被挂起

https://github.com/hughfenghen/WebAV/assets/47944401/7331ef30-fbc7-4bc2-a603-a3f305da688b

codesandbox：https://codesandbox.io/p/devbox/webav-test-v5cdcd?file=%2Fsrc%2FApp.vue

**Comment by hughfenghen** [comment]
请提供一个可复现的 https://codesandbox.io/、https://stackblitz.com/ 项目

**Comment by teyra** [comment]
https://codesandbox.io/p/github/teyra/webav-test/main?workspaceId=8d6b76ba-e756-42fa-af9d-82e0b8962912

**Comment by teyra** [comment]
![image](https://github.com/hughfenghen/WebAV/assets/47944401/c02efabf-c66a-4d62-a6fd-991fa60b7432)


https://codesandbox.io/p/github/teyra/webav-test/main?file=%2Fvite.config.ts&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clus112r00006356ho90uwc5v%2522%252C%2522sizes%2522%253A%255B60%252C40%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clus112r00002356hzn6zm5e3%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clus112r00004356h7068v2r2%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clus112r00005356hm865cd6v%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clus112r00002356hzn6zm5e3%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clus112r00001356hpsn5wl79%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clus1awtp0002356h3kzz7uu2%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Fviews%252FHomeView.vue%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A25%252C%2522startColumn%2522%253A17%252C%2522endLineNumber%2522%253A25%252C%2522endColumn%2522%253A17%257D%255D%257D%252C%257B%2522id%2522%253A%2522clus1z29y0002356h21c5pxqa%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fvite.config.ts%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clus112r00002356hzn6zm5e3%2522%252C%2522activeTabId%2522%253A%2522clus1z29y0002356h21c5pxqa%2522%257D%252C%2522clus112r00005356hm865cd6v%2522%253A%257B%2522id%2522%253A%2522clus112r00005356hm865cd6v%2522%252C%2522activeTabId%2522%253A%2522clus127tn00a9356hyqc8735c%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A2222%252C%2522id%2522%253A%2522clus1193z0068356h8ptkogbi%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%252C%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A5173%252C%2522id%2522%253A%2522clus127tn00a9356hyqc8735c%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clus112r00004356h7068v2r2%2522%253A%257B%2522id%2522%253A%2522clus112r00004356h7068v2r2%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clus112r00003356hpsvufu2k%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clus112n2001ndcgf4jua6qhi%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clus112r00003356hpsvufu2k%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

**Comment by teyra** [comment]
sry，codesandbox用的不是很多，浪费您时间了
https://codesandbox.io/p/devbox/webav-test-v5cdcd?file=%2Fsrc%2FApp.vue

**Comment by teyra** [comment]
发现问题所在了，跟我的视频源有关，换了视频源就可以了，感谢回复

**Comment by hughfenghen** [comment]
请提供一下视频源文件，我看看是否有兼容性问题

**Comment by hughfenghen** [comment]
v0.4.3 已修复
