### ISSUE TITLE
建议：是否可按时间步长获取视频的缩略图

### ISSUE THREAD

**Issue by caohongz** [hughfenghen/WebAV#73]
clip.thumbnails()目前只能配置图片宽度，但是如果我想获取素材视频每秒一次的缩略图是不行的，目前应该是写死的，能够给出一个传参来控制？谢谢。

**Comment by caohongz** [comment]
> 为什么需要，场景是什么？

需要开发一个视频编辑器，这部分的功能希望能应用到轨道上视频的缩略图上，但是因为轨道是可以缩放的，所以需要按照每秒一帧的间隔提取缩略图，来保证轨道缩放到最小时候能展示出所有需要的图片
![1712800119176](https://github.com/hughfenghen/WebAV/assets/48698806/3d6dcf17-5bb4-477c-8d34-5ebf5c9de34c)

**Comment by hughfenghen** [comment]
建议使用 `MP4Clip.tick` 获取图像帧转换成图片，这个性能会差一些

**Comment by caohongz** [comment]
> 建议使用 `MP4Clip.tick` 获取图像帧转换成图片，这个相对 thumbnails 获取缩略图性能会差一些

好，我先试一下效率能不能达到要求，谢谢。

**Comment by hughfenghen** [comment]
`MP4Clip.tick` 返回 的 `video` 是一个 VideoFrame，参考 `thumbnails` 的实现将其转换成小图片。
考虑到性能，最好限制提取图像帧的范围，比如时间轴放大后只提取 1～10s。

`thumbnails` 也可以考虑实现按时间步长提取一段时间的图像，看看诉求是否多，或等待一位勇者来实现这个功能。

**Comment by caohongz** [comment]
我修改了mp4-clip.ts中的thumbnails方法的获取samples部分，但是在个别视频解析时候会报错：DOMException: Decoding error，我看不到具体的报错，要怎么排查VideoDecoder为啥解析错误呢？我查看了sample数据并没有发现问题
![image](https://github.com/hughfenghen/WebAV/assets/48698806/7d89df55-f0f2-4b2e-aa13-88351fe249a6)

**Comment by caohongz** [comment]
> 我修改了mp4-clip.ts中的thumbnails方法的获取samples部分，但是在个别视频解析时候会报错：DOMException: Decoding error，我看不到具体的报错，要怎么排查VideoDecoder为啥解析错误呢？我查看了sample数据并没有发现问题 ![image](https://private-user-images.githubusercontent.com/48698806/321907712-7d89df55-f0f2-4b2e-aa13-88351fe249a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5MDkwMTMsIm5iZiI6MTcxMjkwODcxMywicGF0aCI6Ii80ODY5ODgwNi8zMjE5MDc3MTItN2Q4OWRmNTUtZjBmMi00YjJlLWFhMTMtODgzNTFmZTI0OWE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEyVDA3NTgzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExMmRmMzFhMzUzNWMzYWNjMTU2YzQ2ODU3ODY4YjBhY2Q4MjFmZTJlY2Y2M2Q5ODU2ODMzOTViNDUwNTE0NWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0fJeCW-g94SxprSny82jv08lWm2R6BJTY-eep_pvyDA)

而且我发现就算成功了，得到的部分blob展示上去是花屏样式的

**Comment by izkizk8** [comment]
> > 我修改了mp4-clip.ts中的thumbnails方法的获取samples部分，但是在个别视频解析时候会报错：DOMException: Decoding error，我看不到具体的报错，要怎么排查VideoDecoder为啥解析错误呢？我查看了sample数据并没有发现问题 ![image](https://private-user-images.githubusercontent.com/48698806/321907712-7d89df55-f0f2-4b2e-aa13-88351fe249a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5MDkwMTMsIm5iZiI6MTcxMjkwODcxMywicGF0aCI6Ii80ODY5ODgwNi8zMjE5MDc3MTItN2Q4OWRmNTUtZjBmMi00YjJlLWFhMTMtODgzNTFmZTI0OWE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEyVDA3NTgzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExMmRmMzFhMzUzNWMzYWNjMTU2YzQ2ODU3ODY4YjBhY2Q4MjFmZTJlY2Y2M2Q5ODU2ODMzOTViNDUwNTE0NWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0fJeCW-g94SxprSny82jv08lWm2R6BJTY-eep_pvyDA)
> 
> 而且我发现就算成功了，得到的部分blob展示上去是花屏样式的


花屏是因为不是关键帧，不能单独解码，我直接复用了 `VideoFrameFinder`
可以参考一下这个 PR #70

**Comment by caohongz** [comment]
> > > 我修改了mp4-clip.ts中的thumbnails方法的获取samples部分，但是在个别视频解析时候会报错：DOMException: Decoding error，我看不到具体的报错，要怎么排查VideoDecoder为啥解析错误呢？我查看了sample数据并没有发现问题 ![image](https://private-user-images.githubusercontent.com/48698806/321907712-7d89df55-f0f2-4b2e-aa13-88351fe249a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5MDkwMTMsIm5iZiI6MTcxMjkwODcxMywicGF0aCI6Ii80ODY5ODgwNi8zMjE5MDc3MTItN2Q4OWRmNTUtZjBmMi00YjJlLWFhMTMtODgzNTFmZTI0OWE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEyVDA3NTgzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExMmRmMzFhMzUzNWMzYWNjMTU2YzQ2ODU3ODY4YjBhY2Q4MjFmZTJlY2Y2M2Q5ODU2ODMzOTViNDUwNTE0NWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0fJeCW-g94SxprSny82jv08lWm2R6BJTY-eep_pvyDA)
> > 
> > 
> > 而且我发现就算成功了，得到的部分blob展示上去是花屏样式的
> 
> 花屏是因为不是关键帧，不能单独解码，我直接复用了 `VideoFrameFinder` 可以参考一下这个 PR #74

感谢感谢，我看到了你的PR，尝试了一下我这里是OK的。
