### ISSUE TITLE
实测"录制 AVCanvas"，生成的视频会有卡顿感

### ISSUE THREAD

**Issue by xeoshow** [hughfenghen/WebAV#75]
https://hughfenghen.github.io/WebAV/demo/4_2-recorder-avcanvas
测试上面链接的演示例子时，用自己的素材测试时，生成的视频有卡顿感，并且动图gif合成到视频里变成静态的了。
附件的assets.zip包含了实测的素材，另外附件的WebAV-1712997618826.zip解压后是实测生成的视频文件。通过和输入素材video1.mp4进行比较，可以发现明显的卡顿感。

输入的素材：
1. 视频：video1.mp4
2. 图片：extra.png
3. 文字就是用的默认的白色的"示例文字"
4. 音频：bgm.mp3
5. gif动图：good.gif

[assets.zip](https://github.com/hughfenghen/WebAV/files/14965791/assets.zip)

[WebAV-1712997618826.zip](https://github.com/hughfenghen/WebAV/files/14965863/WebAV-1712997618826.zip)

**Comment by hughfenghen** [comment]
> 动图gif合成到视频里变成静态的了

AVCanvas 的 image sprite 还不支持动图，支持动图的是 @webav/av-cliper 下的 ImgClip；  

> 生成的视频有卡顿感

建议先使用 @webav/av-cliper **离屏快速合成视频**，而不是录制；
AVCanvas 的设计目的是用于支持用户可交互的画布，目前用户较少，迭代没有那么频繁，v1.0.0 可能还会有大改。

**Comment by hughfenghen** [comment]
如果你一定要**录制**视频，如果能接受 webm 格式的视频，甚至可以直接使用浏览器自带 API  —— MediaRecorder

**Comment by xeoshow** [comment]
> > 动图gif合成到视频里变成静态的了
> 
> AVCanvas 的 image sprite 还不支持动图，支持动图的是 @webav/av-cliper 下的 ImgClip；
> 
> > 生成的视频有卡顿感
> 
> 建议先使用 @webav/av-cliper **离屏快速合成视频**，而不是录制； AVCanvas 的设计目的是用于支持用户可交互的画布，目前用户较少，迭代没有那么频繁，v1.0.0 可能还会有大改。
我就是先试验的@webav/av-cliper **离屏快速合成视频**，也是使用的同样上面这些素材，发现有卡顿感，才重新找demo看看是否有其他更合适匹配的例子的~

**Comment by xeoshow** [comment]
> 如果你一定要**录制**视频，如果能接受 webm 格式的视频，甚至可以直接使用浏览器自带 API —— MediaRecorder

感觉还是mp4通用方便些 😄

**Comment by hughfenghen** [comment]
提供 @webav/av-cliper 离屏快速合成视频，可复现卡顿的项目

**Comment by xeoshow** [comment]
我这边整理一个最小的demo项目再发出来

**Comment by hughfenghen** [comment]
#60 有推荐

**Comment by xeoshow** [comment]
这个工单并没有解决，为何关闭呢？这个工单不需要额外例子，直接用官方提供的demo，和我给到的那些素材，很容易就复现了。
