### ISSUE TITLE
在使用OffscreenSprite及Combinator将一段音频文件和一段视频文件合并成视频之后，视频可以在浏览器中正常播放并通过进度条控制播放时间，但是将这个视频下载到本地之后通过播放器却无法控制播放时间和快进呢？

### ISSUE THREAD

**Issue by Mik-pan** [hughfenghen/WebAV#89]
`   
     
        const audioSpr = new OffscreenSprite(
            'audioSpr',
            new AudioClip((await fetch(audioSrc)).body, {
                loop: false
            })
        )

        const videoSpr = new OffscreenSprite(
            'videoSpr',
            new MP4Clip((await fetch(videoSrc)).body)
        )

        const com = new Combinator({
            width: this.options.width,
            height: this.options.height
        })
        
        await com.add(videoSpr, { duration: mergeDuration, main: true })
        await com.add(audioSpr)

        const blob = await new Response(com.output() ?? com).blob()
        const videourl = URL.createObjectURL(blob)
`

**Comment by hughfenghen** [comment]
#60 请参考优化 issue 样式问题

**Comment by hughfenghen** [comment]
本地不行是播放器兼容性问题，参考  #20

**Comment by Mik-pan** [comment]
明白，我参考了一下[#20 ]，应该可以解决这个问题，谢谢！
