### ISSUE TITLE
webav/avclipper封装探测视频文件大小、时长、格式等基础API

### ISSUE THREAD

**Issue by xeoshow** [hughfenghen/WebAV#93]
webav/avclipper要是可以封装ffmpeg、ffprobe的一些基础功能，比如探测视频文件大小、时长、格式等，很多项目就可以前端搞定，不用传到后端了~

**Comment by hughfenghen** [comment]
@webav/av-cliper 主要设计用于支持音视频剪辑场景；
无法做到像 ffmpeg 那么大而全，简单的探测信息操作，可以考虑直接使用 ffmpeg.wasm。

**Comment by xeoshow** [comment]
如前面提到，并不是大而全，而是基础功能的API封装，看目前avcliper貌似是没有，毕竟剪辑时通常都需要这些最基础信息，如果前端直接能获得，不需要再和后端或第三方ffmpeg.wasm，会方便简洁很多

**Comment by hughfenghen** [comment]
av-cliper 假设用户知道素材的格式，已支持的格式实例化后， 通过 meta （如 mp4Clip.meta）获取元信息。

**Comment by xeoshow** [comment]
通过 meta （如 mp4Clip.meta）获取元信息，这个对于使用webav的用户来说，可以直接调用吗？如果可以，确实直接用也挺好。但建议可以文档补充提及下，相当于融合在webav的包功能里了。
