### ISSUE TITLE
现在webav整个系统，貌似没有太系统化的错误日志体系

### ISSUE THREAD

**Issue by xeoshow** [hughfenghen/WebAV#95]
我们也碰到类似下面情况，测试时卡住不动，不知道底层发生了啥。希望至少可以有选项开启错误日志报错的信息。

https://github.com/hughfenghen/WebAV/issues/71
https://github.com/hughfenghen/WebAV/issues/83

**Comment by hughfenghen** [comment]
合成卡住的问题，已经添加了 错误日志。https://github.com/hughfenghen/WebAV/blob/3a19b499113f87a6ff98e35e9a367b3fb9f77034/packages/av-cliper/src/clips/mp4-clip.ts#L203

关于系统化的日志体系，欢迎 PR。
