### ISSUE TITLE
av-canvas 支持视频剪辑场景

### ISSUE THREAD

**Issue by heptagonnnn** [hughfenghen/WebAV#97]
期待av-canvas额外支持以下功能

1. 支持加载不同类型的素材（音视频、图片、文字）
2. 支持控制素材的时间偏移，以控制素材在视频中出现的时间
3. 支持将添加的素材，根据设置的空间坐标、时间偏移导出成视频文件
4. 支持根据设置的空间坐标、时间偏移，预览视频导出后的效果

**Comment by hughfenghen** [comment]
v0.9 基本满足诉求 #103
