### ISSUE TITLE
咨询：Combinator可否返回合成的视频流？

### ISSUE THREAD

**Issue by caohongz** [hughfenghen/WebAV#99]
我的使用场景是实时播放多个视频，是否可以合成视频时候实时返回视频流或者VideoFrame呢？要处理的视频可能会比较长，所以等待合成结束就太久了，谢谢。

我通过修改combinator.ts，添加一个emit的函数，在处理过程中可以将VideoFrame输出出来，但是感觉这样会造成内存溢出或其他不可控的问题。

**Comment by hughfenghen** [comment]
实时播放的多个视频，直接绘制到 canvas，然后调用 `canvas.captureStream()` 即可，没必要使用 Combinator。

**Comment by caohongz** [comment]
> 实时播放的多个视频，直接绘制到 canvas，然后调用 `canvas.captureStream()` 即可，没必要使用 Combinator。

因为我最终需要的效果就是在canvas上绘制，你的意思是直接通过tick获取帧绘制吗？按照30帧视频的情况，多个一起绘制感觉还要保证顺序，感觉性能上会有问题呢，所以才想用Combinator，能更好的控制层级关系，还能配置不同视频的大小位置这些属性。

**Comment by hughfenghen** [comment]
建议先了解下 Web 平台的音视频 API： https://github.com/hughfenghen/WebAV-KnowledgeGraph

选择合适的路径去实现你想要的功能；Combinator 用于**快速合成视频文件**，跟绘制关系不大。

**Comment by caohongz** [comment]
> 建议先了解下 Web 平台的音视频 API： https://github.com/hughfenghen/WebAV-KnowledgeGraph
> 
> 选择合适的路径去实现你想要的功能；Combinator 用于**快速合成视频文件**，跟绘制关系不大。

好的，音视频处理方面确实没什么经验，还在学习
